#!/usr/bin/env node
// Keeps docs/DECISIONS.md navigable as it grows (D-106).
//
//   npm run decisions
//
// 1. Gives every `## D-NNN` heading an explicit anchor, `<a id="d-nnn"></a>`.
//    The repository links to entries as `DECISIONS.md#d-050` — dozens of
//    times — and GitHub's own anchor for a heading is its whole text
//    (`#d-050--a-controls-boundary-is-…`), so every one of those links was
//    landing at the top of a 400 KB file. Idempotent: an anchor already
//    there is left alone.
// 2. Writes docs/DECISIONS-INDEX.md: one line per entry, which is what a
//    session reads first, opening in full only the entries its work touches.
//
// tests/unit/decisions-index.test.ts fails when either is stale, naming this
// command — a guard ships with the command that satisfies it (D-054 §2).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const LOG = join(ROOT, 'docs/DECISIONS.md');
const INDEX = join(ROOT, 'docs/DECISIONS-INDEX.md');

const HEADING = /^## (D-(\d{3,})) — (.+)$/;

/** Every entry: its id, number, title and date, in file order. */
export function readDecisions(src) {
  const lines = src.split('\n');
  const out = [];
  lines.forEach((line, i) => {
    const m = HEADING.exec(line);
    if (!m) return;
    const meta = lines.slice(i + 1, i + 6).join(' ');
    const date = /\*\*Date:\*\* (\d{4}-\d{2}-\d{2})/.exec(meta)?.[1] ?? '';
    out.push({ id: m[1], number: Number(m[2]), title: m[3].trim(), date });
  });
  return out;
}

const anchorFor = (id) => `<a id="${id.toLowerCase()}"></a>`;

/** The log with an anchor line before every heading that lacks one. */
export function withAnchors(src) {
  const lines = src.split('\n');
  const out = [];
  lines.forEach((line, i) => {
    const m = HEADING.exec(line);
    if (m) {
      const anchor = anchorFor(m[1]);
      // `<a id>` then a blank line then the heading: on one line with no
      // blank between, the heading would be swallowed into the paragraph.
      if (!(lines[i - 2] === anchor && lines[i - 1] === '')) out.push(anchor, '');
    }
    out.push(line);
  });
  return out.join('\n');
}

export function renderIndex(decisions) {
  const rows = decisions
    .map((d) => `| [${d.id}](DECISIONS.md#${d.id.toLowerCase()}) | ${d.date} | ${d.title.replace(/\|/g, '\\|')} |`)
    .join('\n');
  return `# Decisions — index

One line per entry in [DECISIONS.md](DECISIONS.md), oldest first:
${decisions.length} entries. **Generated by \`npm run decisions\`; do not edit by
hand** — \`tests/unit/decisions-index.test.ts\` fails when it is stale.

Read this whole index before touching anything, then open in full every entry
whose title touches your work: they are rulings to extend, not to re-litigate
(CLAUDE.md, D-106). An entry's title is its summary — the log's own convention
— so the index is the log's table of contents, not a paraphrase of it.

| # | Date | Decision |
| --- | --- | --- |
${rows}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const src = readFileSync(LOG, 'utf8');
  const anchored = withAnchors(src);
  if (anchored !== src) writeFileSync(LOG, anchored);
  const decisions = readDecisions(anchored);
  writeFileSync(INDEX, renderIndex(decisions));
  console.log(
    `${decisions.length} decisions indexed in docs/DECISIONS-INDEX.md` +
      (anchored !== src ? `; anchors added to docs/DECISIONS.md` : ''),
  );
}
