import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { readDecisions, renderIndex, withAnchors } from '../../scripts/decisions-index.mjs';

/**
 * docs/DECISIONS-INDEX.md is what a session reads first (D-106), so a stale
 * one is worse than none: it says a ruling does not exist. And the anchors
 * are what every `DECISIONS.md#d-050` link in the repository lands on.
 * Both are regenerated by one command, which every failure here names.
 */

const log = readFileSync('docs/DECISIONS.md', 'utf8');
const decisions = readDecisions(log);

describe('the decision log and its index', () => {
  it('reads every entry', () => {
    // Vacuous if the heading pattern stops matching.
    expect(decisions.length).toBeGreaterThan(100);
  });

  it('numbers entries once each, in order, with no gap — two branches appending the same number fail here', () => {
    expect(decisions.map((d) => d.number)).toEqual(decisions.map((_, i) => i + 1));
  });

  it('dates every entry', () => {
    expect(decisions.filter((d) => !d.date).map((d) => d.id)).toEqual([]);
  });

  it('anchors every heading, so `DECISIONS.md#d-nnn` links land (run `npm run decisions`)', () => {
    expect(withAnchors(log) === log, 'an entry has no anchor: run `npm run decisions`').toBe(true);
  });

  it('is indexed as it stands (run `npm run decisions`)', () => {
    const index = readFileSync('docs/DECISIONS-INDEX.md', 'utf8');
    expect(index, 'docs/DECISIONS-INDEX.md is stale: run `npm run decisions`').toBe(renderIndex(decisions));
  });
});
